export const DRIVE_STAGES = Object.freeze({
  DRAFT: 'draft',
  PUBLISHED: 'published',
  APPLICATIONS_OPEN: 'applications_open',
  APPLICATIONS_CLOSED: 'applications_closed',
  TEST_SCHEDULED: 'test_scheduled',
  INTERVIEW_SCHEDULED: 'interview_scheduled',
  RESULTS_PUBLISHED: 'results_published',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
});

export const DRIVE_STAGE_LABELS = Object.freeze({
  [DRIVE_STAGES.DRAFT]: 'Draft',
  [DRIVE_STAGES.PUBLISHED]: 'Published',
  [DRIVE_STAGES.APPLICATIONS_OPEN]: 'Applications Open',
  [DRIVE_STAGES.APPLICATIONS_CLOSED]: 'Applications Closed',
  [DRIVE_STAGES.TEST_SCHEDULED]: 'Test Scheduled',
  [DRIVE_STAGES.INTERVIEW_SCHEDULED]: 'Interview Scheduled',
  [DRIVE_STAGES.RESULTS_PUBLISHED]: 'Results Published',
  [DRIVE_STAGES.COMPLETED]: 'Completed',
  [DRIVE_STAGES.CANCELLED]: 'Cancelled',
});

export const ALLOWED_DRIVE_TRANSITIONS = Object.freeze({
  [DRIVE_STAGES.DRAFT]: [DRIVE_STAGES.PUBLISHED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.PUBLISHED]: [DRIVE_STAGES.APPLICATIONS_OPEN, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.APPLICATIONS_OPEN]: [DRIVE_STAGES.APPLICATIONS_CLOSED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.APPLICATIONS_CLOSED]: [DRIVE_STAGES.TEST_SCHEDULED, DRIVE_STAGES.INTERVIEW_SCHEDULED, DRIVE_STAGES.RESULTS_PUBLISHED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.TEST_SCHEDULED]: [DRIVE_STAGES.INTERVIEW_SCHEDULED, DRIVE_STAGES.RESULTS_PUBLISHED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.INTERVIEW_SCHEDULED]: [DRIVE_STAGES.RESULTS_PUBLISHED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.RESULTS_PUBLISHED]: [DRIVE_STAGES.COMPLETED, DRIVE_STAGES.CANCELLED],
  [DRIVE_STAGES.COMPLETED]: [],
  [DRIVE_STAGES.CANCELLED]: [],
});

export const canTransitionDrive = (from, to) =>
  Boolean(ALLOWED_DRIVE_TRANSITIONS[from || DRIVE_STAGES.DRAFT]?.includes(to));
